### ISSUE TITLE
[1.12] Potential Lang file issue? Maybe not lower cased?

### ISSUE THREAD

**Issue by Boomflex** [GuntherDW/Applied-Energistics-2#11]
Hey Gunther, as discussed on ATC Discord:

https://gyazo.com/32f6e3724715507e47626c2e2632d081

Version that is on the ATC Server/pack.

Anything else just shout at me :)

**Comment by GuntherDW** [comment]
Fixed in 87f6a63f474258278ae1b041192763f6d22af31f
