### ISSUE TITLE
Crash on startup only with forge & AE2

### ISSUE THREAD

**Issue by ARatfat** [GuntherDW/Applied-Energistics-2#4]
Hi, 

Your project looks like more advanced for AE2.

Basically I only have one mod AE2 & I've this crash on startup https://pastebin.com/XrhZixrw 

- Minecraft Version: 1.11.2
- AE2 Version: AE2-alpha5-rv0
- Forge Version: 13.20.1.2388

**Comment by GuntherDW** [comment]
The port to 1.11.2 isn't done yet.
It's still in a high state of flux so crashes are to be expected somewhat until it stabilises a bit.

It's not ready for general consumption just yet.

**Comment by ARatfat** [comment]
sorry I think it was 1.11.2 port sorry

**Comment by GuntherDW** [comment]
It is a port to 1.11.2, but it's not done yet.

**Comment by ARatfat** [comment]
Ok I keep follow the project Thx for your workf

**Comment by ARatfat** [comment]
Before forgort if it's possible play this version witch mc & forge version ?
